<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Prince" failures="1" tests="4" name="Personal Loan" time="0.061" errors="0" timestamp="2025-05-07T14:33:23 EDT">
  <testcase classname="framework.PersonalLoanTestCase" name="personalLoan" time="0.01"/>
  <testcase classname="framework.PersonalLoanTestCase" name="personalLoan" time="0.004"/>
  <testcase classname="framework.PersonalLoanTestCase" name="personalLoan" time="0.002"/>
  <testcase classname="framework.TestRunning" name="Demo2" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at framework.TestRunning.Demo2(TestRunning.java:35)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Demo2 -->
  <testcase classname="framework.TestRunning" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal Loan -->
